### ISSUE TITLE
product backlog

### ISSUE THREAD

**Issue by 9sa6c** [ZoeyYuezy/2020-GPW-L5K1-C#1]

**Comment by 9sa6c** [comment]
Please provide me your feedback

**Comment by ZoeyYuezy** [comment]
Ok

**Comment by ZoeyYuezy** [comment]
In this part，we need to make sure what we need to do first and the next. Decide the task priority. Please give some examples for taking a reference

**Comment by roguegrace** [comment]
> In this part，we need to make sure what we need to do first and the next. Decide the task priority. Please give some examples for taking a reference

First of all, start from design the prototype, design the website framework, finish the requirement step by step, for example, design log in page first, then back-end website, then front-end website.

**Comment by ZoeyYuezy** [comment]
> > In this part，we need to make sure what we need to do first and the next. Decide the task priority. Please give some examples for taking a reference
> 
> First of all, start from design the prototype, design the website framework, finish the requirement step by step, for example, design log in page first, then back-end website, then front-end website.

OK，we can upload some web design pictures and prototype design. And login page，back-end website...we need the code，or find some pictures as  their background.

**Comment by ZoeyYuezy** [comment]
By the way，here is my fezila and PHPmyadmin user account which all of you can create tables and update the files or codes to check the function on the website—Username：zeng-yue2。Password：zhpf6700

**Comment by roguegrace** [comment]
> By the way，here is my fezila and PHPmyadmin user account which all of you can create tables and update the files or codes to check the function on the website—Username：zeng-yue2。Password：zhpf6700

Okay

**Comment by amyzhang7** [comment]
When we think about websites, we need to design data and estimate what data we need. Such as bus routes and staff information. Then, We can choose a framework for the site to modify and discuss.

**Comment by amyzhang7** [comment]
> > By the way，here is my fezila and PHPmyadmin user account which all of you can create tables and update the files or codes to check the function on the website—Username：zeng-yue2。Password：zhpf6700
> 
> Okay

ok

**Comment by amyzhang7** [comment]
> > > In this part，we need to make sure what we need to do first and the next. Decide the task priority. Please give some examples for taking a reference
> > 
> > 
> > First of all, start from design the prototype, design the website framework, finish the requirement step by step, for example, design log in page first, then back-end website, then front-end website.
> 
> OK，we can upload some web design pictures and prototype design. And login page，back-end website...we need the code，or find some pictures as their background.

Ok,we may also need to sort out the specific functions of the site navigation bar.

**Comment by ZoeyYuezy** [comment]
So do you agree that the first priority is making login interface. And think about the priorities of all tasks then we can do them step by step.

**Comment by amyzhang7** [comment]
Of course, we can finish logging into the system first.

**Comment by ZoeyYuezy** [comment]
> Of course, we can finish logging into the system first.

And what is the next？

**Comment by amyzhang7** [comment]
> > Of course, we can finish logging into the system first.
> 
> And what is the next？

We can draw EAD and then design the data associated with the website.

**Comment by roguegrace** [comment]
> > > Of course, we can finish logging into the system first.
> > 
> > 
> > And what is the next？
> 
> We can draw EAD and then design the data associated with the website.

We can use website draw ERD diagram online

**Comment by ZoeyYuezy** [comment]
For the product backlog，we can write the usecase story

**Comment by amyzhang7** [comment]
> > > > Of course, we can finish logging into the system first.
> > > 
> > > 
> > > And what is the next？
> > 
> > 
> > We can draw EAD and then design the data associated with the website.
> 
> We can use website draw ERD diagram online

🆗

**Comment by amyzhang7** [comment]
> For the product backlog，we can write the usecase story

Yes, we can describe it according to the requirements of CBC.

**Comment by ZoeyYuezy** [comment]
[product backlog.xlsx](https://github.com/ZoeyYuezy/2020-GPW-L5K1-C/files/4516483/product.backlog.xlsx)
