### ISSUE TITLE
management system improvements round 1

### ISSUE THREAD

**Issue by amyzhang7** [ZoeyYuezy/2020-GPW-L5K1-C#13]

**Comment by ZoeyYuezy** [comment]
After a design of management system ERD, discuss about the relationship between each entities. And do not make the data redundancy which need to do a 3NF.

**Comment by ZoeyYuezy** [comment]
@roguegrace @lhaoze  Please changes the index2.php of management template. Change the table name and create tables in phpmyadmin.

**Comment by roguegrace** [comment]
> @roguegrace @lhaoze Please changes the index.php of management template. Change the table name and create tables in phpmyadmin.

okay

**Comment by amyzhang7** [comment]
We need to analyze the line data again.Some of the data may not have been properly analyzed.

**Comment by ZoeyYuezy** [comment]
> We need to analyze the line data again.Some of the data may not have been properly analyzed.

Routline data? You can give some other examples which we did not considered.
