### ISSUE TITLE
database design

### ISSUE THREAD

**Issue by ZoeyYuezy** [ZoeyYuezy/2020-GPW-L5K1-C#15]

**Comment by amyzhang7** [comment]
![ERD](https://user-images.githubusercontent.com/45256847/80206626-3d7f7600-865f-11ea-900f-c4b2695d8b49.png)
This is the preliminary ERD design for sales.

**Comment by amyzhang7** [comment]
![erd](https://user-images.githubusercontent.com/45256847/80207177-46bd1280-8660-11ea-9982-1ab4d66c352d.jpg)
This is the preliminary ERD design for sales.

**Comment by ZoeyYuezy** [comment]
I and amy will make some improvements of this preliminary ERD, if you have any suggestions can also let us know.

**Comment by ZoeyYuezy** [comment]
For the improvements, i think there is not need to create a payment table, reserve and order table. Maybe it can create in management interface. Because these tables can looked by all tourists, and these information are privacy, i think these three information can only seen by themselfs.

**Comment by ZoeyYuezy** [comment]
Change 1: Add 'food' table include: ID, Name, Price, etc.
Change 2: Businformation should write bus's information such as the bus number, bus drvier, driver's level, connect tel, bus type.....

Change 3: We can create a 'price' table because these three: ticket, food, customer (because one customer can only order one ticket) need price.

**Comment by ZoeyYuezy** [comment]
And for the order information and other privacy information we can use 'join' phase to acheive our goals. Therefore, we can create customer's information and order information directly.

**Comment by ZoeyYuezy** [comment]
[Sales EAD.pdf](https://github.com/ZoeyYuezy/2020-GPW-L5K1-C/files/4528973/Sales.EAD.pdf)
I' ve made some changes, and you can add something else.

**Comment by roguegrace** [comment]
[ERD-Manager.pdf](https://github.com/ZoeyYuezy/2020-GPW-L5K1-C/files/4551163/ERD-Manager.pdf)

**Comment by lhaoze** [comment]
![image](https://user-images.githubusercontent.com/45256802/80589699-3f757a80-8a4d-11ea-8e12-98f1fd9314bf.png)
![QQ图片20200429191054](https://user-images.githubusercontent.com/45256802/80589721-4b613c80-8a4d-11ea-8bc2-8c0075570db5.png)

**Comment by lhaoze** [comment]
![ERD](https://user-images.githubusercontent.com/45256802/80589921-a3983e80-8a4d-11ea-877b-aa99e9f863c8.png)

**Comment by lhaoze** [comment]
[ERD.docx](https://github.com/ZoeyYuezy/2020-GPW-L5K1-C/files/4551495/ERD.docx)

**Comment by amyzhang7** [comment]
![rountdata](https://user-images.githubusercontent.com/45256847/80594738-27562900-8a56-11ea-8049-cabaf78dddfa.png)
I set up three routes in the pma and they might use join data.
