### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by ZoeyYuezy** [ZoeyYuezy/2020-GPW-L5K1-C#16]

**Comment by ZoeyYuezy** [comment]
In this part, we need to testing all of the system and functions we did. Check if they can work.

**Comment by ZoeyYuezy** [comment]
The function of login page is well till now.

**Comment by ZoeyYuezy** [comment]
Every link in sales interface management is also well, no wrong code and blank pages.

**Comment by amyzhang7** [comment]
The introduction of the place is ok, but the image has not been implemented corresponding
