### ISSUE TITLE
management system improvement round 2

### ISSUE THREAD

**Issue by roguegrace** [ZoeyYuezy/2020-GPW-L5K1-C#17]

**Comment by ZoeyYuezy** [comment]
I have linked index2.php with login.php, you can check use user.sql. There need to make a decision of what tables information you want to display for manager. First, take reference to the reuirement and explore more functions.

**Comment by ZoeyYuezy** [comment]
By the way do not change my login.php, register.html, forgot-password.file in FileZilla and do not change the layout of index2.php. Other html related to index2 need to change their style as index2.php!Please finish the basic changes this week. @roguegrace @lhaoze

**Comment by ZoeyYuezy** [comment]
Your table.php may have a wrong oder of volume and routine
![05D1B8E5-9190-4529-B3CD-690F2DFE4678](https://user-images.githubusercontent.com/45254029/81802967-926d2880-9549-11ea-82ec-cd5726558f4d.jpeg)

**Comment by roguegrace** [comment]
> Your table.php may have a wrong oder of volume and routine
> ![05D1B8E5-9190-4529-B3CD-690F2DFE4678](https://user-images.githubusercontent.com/45254029/81802967-926d2880-9549-11ea-82ec-cd5726558f4d.jpeg)

thanks for correcting, i have changed it. 
![image](https://user-images.githubusercontent.com/45253908/81803324-18896f00-954a-11ea-9ef8-2eea11bed889.png)

**Comment by ZoeyYuezy** [comment]
No problem. And think about does the table shows all information of manager‘s requirement.
