### ISSUE TITLE
management system improvements round 3

### ISSUE THREAD

**Issue by lhaoze** [ZoeyYuezy/2020-GPW-L5K1-C#18]

**Comment by lhaoze** [comment]
In this improvements, i have changed the template of management interface to make the back platform more easy to manage information.

**Comment by lhaoze** [comment]
After i upload my code, you can check online.

**Comment by roguegrace** [comment]
> After i upload my code, you can check online.

Ok

**Comment by lhaoze** [comment]
Because some reason of my computer, i have send the code to Zoey to Help me Upload. But when she helped me, there still sea the code is upload by Zoey. And Today i had changed several times. And finally i can upload with the write form. Here is some pictures that can improve.



@jslemmer 



[新建DOCX 文档.docx](https://github.com/ZoeyYuezy/2020-GPW-L5K1-C/files/4701311/DOCX.docx)

**Comment by 9sa6c** [comment]
Ok, thank you for letting me know. But the name of the other student will be used, when you use their computer to upload. Just keep that in mind for the future
