### ISSUE TITLE
routline decision

### ISSUE THREAD

**Issue by lhaoze** [ZoeyYuezy/2020-GPW-L5K1-C#19]

**Comment by 9sa6c** [comment]
Please do not assign ticket to me, but use my name (@jslemmer) when you want to ask a question.

Also add more details in your issues, what is this issue about? I can not see or understand that from only the title.

**Comment by ZoeyYuezy** [comment]
Does it mean we need upload our rouline design which i ever alloted 3 routline design for every member. 

For routline design, sales interface can only see the routline information. And for the management interface, there need to consider that manager can add\update\delete the information. 

Besides, i have already create two tables in my phpmyadmin which named 'bus_information' &'driver'. After the design of your routline, please input your data in the tables.

**Comment by roguegrace** [comment]
![image](https://user-images.githubusercontent.com/45253908/80583311-9f1a5880-8a42-11ea-8baa-b8c0ad0d15ae.png)

**Comment by roguegrace** [comment]
![Routline 1](https://user-images.githubusercontent.com/45253908/80583596-fe786880-8a42-11ea-874d-c9d3f52896e0.png)

**Comment by ZoeyYuezy** [comment]
@roguegrace  can not see your picture, you can put the image into a word document then upload a file.

**Comment by roguegrace** [comment]
[routline.pdf](https://github.com/ZoeyYuezy/2020-GPW-L5K1-C/files/4551161/routline.pdf)

**Comment by amyzhang7** [comment]
> Does it mean we need upload our rouline design which i ever alloted 3 routline design for every member.
> 
> For routline design, sales interface can only see the routline information. And for the management interface, there need to consider that manager can add\update\delete the information.
> 
> Besides, i have already create two tables in my phpmyadmin which named 'bus_information' &'driver'. After the design of your routline, please input your data in the tables.

ok

**Comment by amyzhang7** [comment]
![rountdata](https://user-images.githubusercontent.com/45256847/80594954-8320b200-8a56-11ea-8d02-8a7fc6160fee.png)
I set up three routes in the pma and they might use join data.

**Comment by lhaoze** [comment]
[Roudline.docx](https://github.com/ZoeyYuezy/2020-GPW-L5K1-C/files/4552548/Roudline.docx)

**Comment by ZoeyYuezy** [comment]
@amyzhang7  your image also can not see, please upload again.

**Comment by ZoeyYuezy** [comment]
I see Devin create a table 'routline' in my phpmyadmin, and that table is well for management system. So Althas can add your routline design in 'routline', after that you can make some improvements. Zoey and amy are design for sales system with table 'bus information' which include routline.
