### ISSUE TITLE
prototype improvements

### ISSUE THREAD

**Issue by ZoeyYuezy** [ZoeyYuezy/2020-GPW-L5K1-C#2]

**Comment by ZoeyYuezy** [comment]
What other functions do we  need to consider.

**Comment by lhaoze** [comment]
We should take into account the functions of the customer to check the route, ticket balance and payment method

**Comment by ZoeyYuezy** [comment]
Zoey and Amy need to create ERD diagram to see what the relationships between entities(requirement anlysis)  with sales system interface.
Devin and Althas need to create ERD diagram to see what the relationships between entities(requirement anlysis)  with sales system interface.

**Comment by ZoeyYuezy** [comment]
After that, create tables for the interface.
