### ISSUE TITLE
database improvement

### ISSUE THREAD

**Issue by ZoeyYuezy** [ZoeyYuezy/2020-GPW-L5K1-C#20]
After your database design and routline design, i have already make them together and had normalizated some tables information, here is an appendix for you to check if there still exsis some data redundancy and lack some important information. Please give me feedback.
[database improvements.docx](https://github.com/ZoeyYuezy/2020-GPW-L5K1-C/files/4555970/database.improvements.docx)

**Comment by ZoeyYuezy** [comment]
• Costs for tickets are calculated by distance and ticket level.
 1, Economy: every 50 km on a bus costs: 25 RMB 
 2, Business: every 50 km on a bus costs: 95 RMB

**Comment by ZoeyYuezy** [comment]
Please improve the database design and implement them in phpmyadmin and using Brackets to create php file. @amyzhang7 @lhaoze

**Comment by lhaoze** [comment]
As for the route design, do we need to show the heat of each route by some ICONS, or directly show the popularity of the route by the sales volume

**Comment by ZoeyYuezy** [comment]
> As for the route design, do we need to show the heat of each route by some ICONS, or directly show the popularity of the route by the sales volume

Well, i think we can directly show the most popular route by the sales volume. If you want to show the popular route by ICONS, how you display the icons with tables? 

And what are your ideas? @roguegrace @amyzhang7

**Comment by amyzhang7** [comment]
> > As for the route design, do we need to show the heat of each route by some ICONS, or directly show the popularity of the route by the sales volume
> 
> Well, i think we can directly show the most popular route by the sales volume. If you want to show the popular route by ICONS, how you display the icons with tables?
> 
> And what are your ideas? @roguegrace @amyzhang7
Ok, I think we can adjust the departure time and the number of cars according to the time period.
So you adopt the second one which is directly show the data in tables
