### ISSUE TITLE
Requirement analysis for management interface

### ISSUE THREAD

**Issue by roguegrace** [ZoeyYuezy/2020-GPW-L5K1-C#25]
For this part, we should define the requirement for management interface, such as, how many tables we should create, how many charts we should draw, and relationship between manager and customer, etc.

@roguegrace @ZoeyYuezy @lhaoze @amyzhang7

**Comment by ZoeyYuezy** [comment]
This is already done in ERD and requirement analysis process.

**Comment by ZoeyYuezy** [comment]
But you can make your database more specific and improve its function and relationship.

**Comment by amyzhang7** [comment]
Yes, we can design staff information and need some manage databases function.

**Comment by ZoeyYuezy** [comment]
> Yes, we can design staff information and need some manage databases function.

Can more detail? What function?

**Comment by ZoeyYuezy** [comment]
• Manager must be able to see a list of all tickets sold on a specific day
• Manager must be able to see an ordered list of which traveler spend the most money on bus tickets in a specific month
• Manager must be able to see a dashboard of: o Amount of tickets sold o Daily revenue o Most popular destination o And more… )

**Comment by amyzhang7** [comment]
> > Yes, we can design staff information and need some manage databases function.
> 
> Can more detail? What function?

For example, manager can add employee information, salaries, and department assignments.
Manage the number of tickets.

**Comment by lhaoze** [comment]
Can we satisfy all the requirements by a table, with the date as the standard, showing its sales, heat and orders for each date?
Instead of making separate tables of sales, heat and orders.
I think the first way is more intuitive to understand the details of each day.

**Comment by ZoeyYuezy** [comment]
> Can we satisfy all the requirements by a table, with the date as the standard, showing its sales, heat and orders for each date?
> Instead of making separate tables of sales, heat and orders.
> I think the first way is more intuitive to understand the details of each day.

Sure, and you can design for it which we will more clear of your thoughts and more easy for you to implement the interface.

**Comment by ZoeyYuezy** [comment]
The management system need to **manage routes and schedules of staff.** 

Including a part wherein the senior managers of the CBC **can observe sales and analyse management information**

**Comment by roguegrace** [comment]
How to achieve "forget password" function.

**Comment by ZoeyYuezy** [comment]
> How to achieve "forget password" function.

There is a forget password.html in the code file and it can work. Also，there can register a new account with register.html
![C6098B90-DBD5-43B9-AF84-073D1EF587B6](https://user-images.githubusercontent.com/45254029/81802664-1246c300-9549-11ea-9557-31bb1de3e7bb.jpeg) 

![9324B814-71CC-48C5-BA73-4C2F8BCB462A](https://user-images.githubusercontent.com/45254029/81802653-0bb84b80-9549-11ea-8f96-a7b5df9d69dc.jpeg)
