### ISSUE TITLE
upload issues

### ISSUE THREAD

**Issue by roguegrace** [ZoeyYuezy/2020-GPW-L5K1-C#26]
you can discuss any problems encountered when upload code in this issue

**Comment by roguegrace** [comment]
![image](https://user-images.githubusercontent.com/45253908/81035529-ef276e00-8ecd-11ea-868e-e12c19492ccb.png)
I use desktop upload our management-template code, but it not shows on github website. 
https://user-images.githubusercontent.com/45253908/81035529-ef276e00-8ecd-11ea-868e-e12c19492ccb.png
And it shows on pull requests, i do not know what is meaning, it is supposed to be in code area.
if you guys know solution, please help me, thanks.

**Comment by ZoeyYuezy** [comment]
You create four new branchs which is use for us to upload our code in this branch. You should directly upload the management interface's code on website. Although there is a way to use the desktop to upload, directly upload them using website github may more easier.
