### ISSUE TITLE
task allot

### ISSUE THREAD

**Issue by ZoeyYuezy** [ZoeyYuezy/2020-GPW-L5K1-C#3]
Discuss about the project requirements and chose the part we want to do or do all things together.

**Comment by ZoeyYuezy** [comment]
In project planning， we should discuss what requirements we need in our program. Allot the tasks or work together. Give a reply.

**Comment by roguegrace** [comment]
In the first stage, we should design the user interface, home page, in this phase, i would like to responsible for designing home page.

**Comment by ZoeyYuezy** [comment]
> In the first stage, we should design the user interface, home page, in this phase, i would like to responsible for designing home page.

homepage for tourists or managers

**Comment by roguegrace** [comment]
> > In the first stage, we should design the user interface, home page, in this phase, i would like to responsible for designing home page.
> 
> homepage for tourists or managers

Both of them

**Comment by ZoeyYuezy** [comment]
> > > In the first stage, we should design the user interface, home page, in this phase, i would like to responsible for designing home page.
> > 
> > 
> > homepage for tourists or managers
> 
> Both of them

👌

**Comment by ZoeyYuezy** [comment]
> > > > In the first stage, we should design the user interface, home page, in this phase, i would like to responsible for designing home page.
> > > 
> > > 
> > > homepage for tourists or managers
> > 
> > 
> > Both of them
> 
> 👌

emm，there need two user interface，and detail functions are in the user interface. In my opinion，homepage is more similar to user interface. I don’t understand because we already have a templet. Or  you just mean that you design the homepage interface which is change some name of navigation bar and insert relevant pictures without any IT function.

**Comment by roguegrace** [comment]
> > > > > In the first stage, we should design the user interface, home page, in this phase, i would like to responsible for designing home page.
> > > > 
> > > > 
> > > > homepage for tourists or managers
> > > 
> > > 
> > > Both of them
> > 
> > 
> > 👌
> 
> emm，there need two user interface，and detail functions are in the user interface. In my opinion，homepage is more similar to user interface. I don’t understand because we already have a templet. Or you just mean that you design the homepage interface which is change some name of navigation bar and insert relevant pictures without any IT function.

that is what i mean, use the template user interface and homepage , and change the text, imagine, and information of navigation bar.

**Comment by amyzhang7** [comment]
> > > > > > 在第一阶段，我们应该设计用户界面主页，在这一阶段，我要负责设计主页。
> > > > > 
> > > > > 
> > > > > 游客或管理者的主页
> > > > 
> > > > 
> > > > 两个都
> > > 
> > > 
> > > 👌
> > 
> > 
> > 嗯，需要两个用户界面，并且用户界面中有详细功能。在我看来，主页更类似于用户界面。我不明白，因为我们已经有了神庙。或者，您只是意味着您设计了主页界面，即更改了导航栏的名称并插入了没有任何IT功能的相关图片。
> 
> 这就是我的意思，使用模板用户界面和主页，并更改导航栏的文本，想象和信息。



> > > > > > In the first stage, we should design the user interface, home page, in this phase, i would like to responsible for designing home page.
> > > > > 
> > > > > 
> > > > > homepage for tourists or managers
> > > > 
> > > > 
> > > > Both of them
> > > 
> > > 
> > > 👌
> > 
> > 
> > emm，there need two user interface，and detail functions are in the user interface. In my opinion，homepage is more similar to user interface. I don’t understand because we already have a templet. Or you just mean that you design the homepage interface which is change some name of navigation bar and insert relevant pictures without any IT function.
> 
> that is what i mean, use the template user interface and homepage , and change the text, imagine, and information of navigation bar.

I can consider the specific functions that the visitor page needs. For example, buying tickets, paying and checking bus routes.

**Comment by amyzhang7** [comment]
> > > > > > In the first stage, we should design the user interface, home page, in this phase, i would like to responsible for designing home page.
> > > > > 
> > > > > 
> > > > > homepage for tourists or managers
> > > > 
> > > > 
> > > > Both of them
> > > 
> > > 
> > > 👌
> > 
> > 
> > emm，there need two user interface，and detail functions are in the user interface. In my opinion，homepage is more similar to user interface. I don’t understand because we already have a templet. Or you just mean that you design the homepage interface which is change some name of navigation bar and insert relevant pictures without any IT function.
> 
> that is what i mean, use the template user interface and homepage , and change the text, imagine, and information of navigation bar.

I can consider the specific functions that the visitor page needs. For example, buying tickets, paying and checking bus routes.

**Comment by ZoeyYuezy** [comment]
> > > > > > > In the first stage, we should design the user interface, home page, in this phase, i would like to responsible for designing home page.
> > > > > > 
> > > > > > 
> > > > > > homepage for tourists or managers
> > > > > 
> > > > > 
> > > > > Both of them
> > > > 
> > > > 
> > > > 👌
> > > 
> > > 
> > > emm，there need two user interface，and detail functions are in the user interface. In my opinion，homepage is more similar to user interface. I don’t understand because we already have a templet. Or you just mean that you design the homepage interface which is change some name of navigation bar and insert relevant pictures without any IT function.
> > 
> > 
> > that is what i mean, use the template user interface and homepage , and change the text, imagine, and information of navigation bar.
> 
> I can consider the specific functions that the visitor page needs. For example, buying tickets, paying and checking bus routes.

do more details

**Comment by ZoeyYuezy** [comment]
So i will create a user table in the phpmyadmin and write a login.php for both tourists and managers this week.

**Comment by ZoeyYuezy** [comment]
What you will do in this week.

**Comment by amyzhang7** [comment]
> What you will do in this week.

Our team can finish the main interface of the sales system, the login interface and modify the basic framework this week. I will design the login interface.

**Comment by roguegrace** [comment]
> What you will do in this week.

I can finish the database parts, create table for data of website

**Comment by ZoeyYuezy** [comment]
> > What you will do in this week.
> 
> I can finish the database parts, create table for data of website

for user interface？

**Comment by ZoeyYuezy** [comment]
1. 10 Bus routes design (in the sales interface, add pictures and routlines)--Every member need to design 3 routlines
2. sales interface design & database design(need to think how to easily sell tickets for customers)---Zoey and Amy design ERD first, then do the details together.
3. management interface design & database design----Devin and Althas design ERD first, after that allote details to every member.

!!!(system design need to take the Appendix as a reference)!!!
After finish the part of sales and management, two-two to improvement the website and work to create a working system.
