### ISSUE TITLE
Route page border issue

### ISSUE THREAD

**Issue by amyzhang7** [ZoeyYuezy/2020-GPW-L5K1-C#31]
In the route page, I tried to modify the border, but the data table did not show well.
I think another layout may be needed.

**Comment by ZoeyYuezy** [comment]
Another layout？ The border issue may the code issue, you should  try several times to test the code. Some times, the css style in each php file is different, please careful.

**Comment by ZoeyYuezy** [comment]
And if you have any code issues you can ask jons to help you with pictures. And you need @ him in that issue.

**Comment by ZoeyYuezy** [comment]
![image](https://user-images.githubusercontent.com/45254029/81188138-8d5b2700-8fe7-11ea-8898-9263d7db009a.png)
I have check you routline.php, it need to changen css and put right data in the related table.

**Comment by amyzhang7** [comment]
> ![image](https://user-images.githubusercontent.com/45254029/81188138-8d5b2700-8fe7-11ea-8898-9263d7db009a.png)
> I have check you routline.php, it need to changen css and put right data in the related table.

ok
