### ISSUE TITLE
sales system requirements analysis

### ISSUE THREAD

**Issue by ZoeyYuezy** [ZoeyYuezy/2020-GPW-L5K1-C#33]
Analysis the sales system's detail here! What we need to display for our guest.

**Comment by ZoeyYuezy** [comment]
Users must be able to select a start and end destination
• Users must be able to select different tickets levels **(economy or business)**
 o Each ticket level has a different capacity**(this is not considered before)**
• Users must can only buy 1 ticket at a time**(This is also do not display on the website)**
• User in must be able to buy a meal for on the bus. **(consider a range of different meals)**
• Users are required to record personal identification information for each ticket
• Users must be able to record payment from different payment methods **(Cash, bank card, Alipay, Wechat)**
• Costs for tickets are calculated by distance and ticket level o Economy: 

**> every 50 km on a bus costs: 25 RMB o Business: every 50 km on a bus costs: 95 RMB**

**Comment by ZoeyYuezy** [comment]
Wecome to give some advice for us @roguegrace @lhaoze

**Comment by ZoeyYuezy** [comment]
A working information system for selling bus tickets.**Make sure the order system can work!**

**Comment by roguegrace** [comment]
I think the sale system should show different types of tickets, and the information of tickets should shows on a table, and food could be a set meal, economy and business tickets have two levels of meal, business tickets should be better than economy, then choose mode of payment , after customer purchase their tickets, then turn to a new page, bill page, customer can check personal information and bill details, include cost, payment methods, etc.

**Comment by ZoeyYuezy** [comment]
> I think the sale system should show different types of tickets, and the information of tickets should shows on a table, and food could be a set meal, economy and business tickets have two levels of meal, business tickets should be better than economy, then choose mode of payment , after customer purchase their tickets, then turn to a new page, bill page, customer can check personal information and bill details, include cost, payment methods, etc.

It means that the food is free to offer to our customers by different levels？ But there need to consider many types of meals which the customers can have choice. Is there necessary for set two level meals for customer？

**Comment by ZoeyYuezy** [comment]
I think we need to create a more specific ERD for the basic requirements and think about how to normalization the data and try our best to make the data do not redundancy @amyzhang7

**Comment by amyzhang7** [comment]
> I think we need to create a more specific ERD for the basic requirements and think about how to normalization the data and try our best to make the data do not redundancy @amyzhang7

Of course, we can modify it again according to the previous ERD
