### ISSUE TITLE
Server environment & database

### ISSUE THREAD

**Issue by 9sa6c** [ZoeyYuezy/2020-GPW-L5K1-C#35]
I have created a new server environment and database for you to upload and test your project

URL: l5k1c.instantcloud.cn

User: l5k1c
Password: huZ83ztGODxNejlkPoNR

DB name: l5k1c
DB user: 7e7d2464769d
DB pass: 270bfc6d134fe22e

**Comment by roguegrace** [comment]
okay，we’ll try later

**Comment by ZoeyYuezy** [comment]
ok

**Comment by amyzhang7** [comment]
ok

**Comment by ZoeyYuezy** [comment]
I have already upload the code on this Server
