### ISSUE TITLE
issues when using git hub desktop

### ISSUE THREAD

**Issue by roguegrace** [ZoeyYuezy/2020-GPW-L5K1-C#36]
i try upload code into github desktop, but it shows follows picture, and i do not know how to solve it, if you guys know solution, please contact me.
![image](https://user-images.githubusercontent.com/45253908/82459307-5c501b80-9aea-11ea-98da-05af1b1e73a9.png)

**Comment by ZoeyYuezy** [comment]
You need to pull the code down first, because i have update the new code and files. Then you can change your code.
