### ISSUE TITLE
For Essay Question

### ISSUE THREAD

**Issue by ZoeyYuezy** [ZoeyYuezy/2020-GPW-L5K1-C#37]
The Contents

**Comment by ZoeyYuezy** [comment]
hello sir, is this mean we need to write agile pactice&Teamwork in our essay to demonstrate how we corporate together. Or we just need to demostrate what the fuction of every pages and the development of our database and ethic issues. 
![image](https://user-images.githubusercontent.com/45254029/83044197-72278880-a076-11ea-8765-76ca6e4f15bf.png)
  @jslemmer

**Comment by amyzhang7** [comment]
hello sir，What are the specific aspects of development and database? And need to talk about team agile development? Does the data part need to represent the data of the whole system?And the interrelationship?By using the ERD diagram?@jslemmer

**Comment by 9sa6c** [comment]
> hello sir, is this mean we need to write agile pactice&Teamwork in our essay to demonstrate how we corporate together. Or we just need to demostrate what the fuction of every pages and the development of our database and ethic issues.
> ![image](https://user-images.githubusercontent.com/45254029/83044197-72278880-a076-11ea-8765-76ca6e4f15bf.png)
> @jslemmer

No need to write about it, I need to see it in the github. How much did you cooperate together in here. How was your project planning, working in issues, adding code with github desktop, ect

**Comment by 9sa6c** [comment]
> hello sir，What are the specific aspects of development and database? And need to talk about team agile development? Does the data part need to represent the data of the whole system?And the interrelationship?By using the ERD diagram?@jslemmer

I will look at your database and your code. If I feel you have done an excellent job, this level will be awarded. But for that I expect you to implement more functions and features than setout in the requirements.

As for point 2 of the report. Yes, I do want you to show and explain me your ERD there.
You do not need to talk about agile development in your report. I need to see that here on github
