### ISSUE TITLE
For the data part of the report

### ISSUE THREAD

**Issue by amyzhang7** [ZoeyYuezy/2020-GPW-L5K1-C#38]
What needs to be described?

**Comment by amyzhang7** [comment]
I think data includes system analysis, system requirements, business processes, modeling and database design. What do you think? @ZoeyYuezy

**Comment by lhaoze** [comment]
I think so. And we need to allot tasks.

**Comment by ZoeyYuezy** [comment]
Yes, i think so. And we should allot to every one.

**Comment by ZoeyYuezy** [comment]
You and me can write database part. Devin write website demo. And Arthas write Ethics. @amyzhang7 @roguegrace @lhaoze

**Comment by amyzhang7** [comment]
> You and me can write database part. Devin write website demo. And Arthas write Ethics. @amyzhang7 @roguegrace @lhaoze

ok

**Comment by amyzhang7** [comment]
![G6TKKS)KXCH5WN(Q9U7Y~OV](https://user-images.githubusercontent.com/45256847/83343701-7383da00-a330-11ea-9f4f-b23cc3731dcd.png)
Determine the specific data according to the model
