### ISSUE TITLE
website templet decision

### ISSUE THREAD

**Issue by ZoeyYuezy** [ZoeyYuezy/2020-GPW-L5K1-C#4]
You can find some good templet and upload the link，we can discuss which one is better for our project. If there is no other templet better，then the templet which i found will become the final templet. Here is the link：http://www.cssmoban.com/cssthemes/5655.shtml

**Comment by roguegrace** [comment]
All of these template is fine, the template Zoey found is better to satisfy our project requirement at present.

**Comment by ZoeyYuezy** [comment]
Desktop GitHub files can be cloned and then automatically generates a folder to local, and then you can change the code with your own Brackets. Then you can upload the new files to fezilla and you can also add tables in phpmyadmin. After that you can update the code on the webpage GitHub.
If there is a better way to update code，please share.

**Comment by amyzhang7** [comment]
We can select a framework from zoey's link. It can be suitable for our information system design of CBC.
