### ISSUE TITLE
prototype design

### ISSUE THREAD

**Issue by ZoeyYuezy** [ZoeyYuezy/2020-GPW-L5K1-C#6]
After initial design of every small part，collet them together and make some changes or upgrade.

**Comment by ZoeyYuezy** [comment]
We have delete some codes which we did not need in our templet and add some images and codes to close the project which we would like to finish. Therefore, this prototype design issue is finished.

**Comment by amyzhang7** [comment]
> We have delete some codes which we did not use in our templet and add some images and codes to close the project which we would like to finish. Therefore, this prototype design issue is finished.

OK
