### ISSUE TITLE
template modify

### ISSUE THREAD

**Issue by roguegrace** [ZoeyYuezy/2020-GPW-L5K1-C#8]
It is important that how to change information of template, there is no perfect template for our project which is actually satisfy all requirement, so, based on the requirement of our project, change relevant content and add function to make sure the website can operate normally and satisfy requirement same time.

**Comment by amyzhang7** [comment]
Yes, we can discuss the specific functions of the website. Divided into several plates.

**Comment by ZoeyYuezy** [comment]
Sure，we need make a lot of changes with the templet. First we can change the easy things like name and logo. Think about what detail function we need during the process when we make the easy changes.

**Comment by lhaoze** [comment]
The plates should need1. All road maps2. Ticket window (including seat class selection and payment method)3. Remaining tickets and departure time

**Comment by ZoeyYuezy** [comment]
By the way, we can directly fix up our code with Brackets, saved and testing by yourself, if it works with what you want, then you can commit them on the desktop github and there is no neccessary to copy the code to the website to change them.
