### ISSUE TITLE
Login Screen

### ISSUE THREAD

**Issue by amyzhang7** [ZoeyYuezy/2020-GPW-L5K1-C#9]
The information of CBC senior management needs to be protected. We can do it the way the user logs in. Perform hierarchical login for different people.

**Comment by ZoeyYuezy** [comment]
That is a good idea for different level，so let’s do it with our Brackets. But first of all, we need crate database then it can link with internet.

**Comment by lhaoze** [comment]
We can join a link in the front, the effect is to be able to let the high-level administrator directly into the background management information, so can prevent information leakage.

**Comment by amyzhang7** [comment]
> That is a good idea for different level，so let’s do it with our Brackets. But first of all, we need crate database then it can link with internet.

Well, we need to make a distinction between employees and managers.

**Comment by amyzhang7** [comment]
> 我们可以在最前面加入一个链接，其作用是能够让高级管理员直接将后台信息导入后台，从而可以防止信息泄露。



> We can join a link in the front, the effect is to be able to let the high-level administrator directly into the background management information, so can prevent information leakage.
Yes, we can design it that way

**Comment by amyzhang7** [comment]
> We can join a link in the front, the effect is to be able to let the high-level administrator directly into the background management information, so can prevent information leakage.

Yes, we can design it that way

**Comment by ZoeyYuezy** [comment]
> We can join a link in the front, the effect is to be able to let the high-level administrator directly into the background management information, so can prevent information leakage.

I don’t understand. Is it mean join a link in the login interface or user interface?How to directly get into the background management information. And why this can avoid information leakage.

**Comment by ZoeyYuezy** [comment]
> > That is a good idea for different level，so let’s do it with our Brackets. But first of all, we need crate database then it can link with internet.
> 
> Well, we need to make a distinction between employees and managers.

👌

**Comment by ZoeyYuezy** [comment]
Here is the link of login.php:https://2201713130225.instantcloud.cn/gpw2/login.php

It can success to login index.php which is level 1, and you can test it with uses.sql. There are usernames and passwords of uses.
